apiVersion: v1
kind: Service
metadata:
  name: seahorsedb
  namespace: default
  labels:
    app: seahorsedb
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: tcp-client
  - port: 16379
    targetPort: 16379
    name: tcp-gossip
  type: ClusterIP
  selector:
    app: seahorsedb